 # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.15.2 is version 31
    loaderVersion="[35,)"
    license="GNU GPLv3"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/ghana7/ExtraCoals/issues"#https://github.com/ghana7/MinecraftCCG/issues"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false

    [[mods]]
      modId="minecraftccg"
      version="1.0.0.0"
      displayName="Minecraft CCG"
      displayURL="https://github.com/ghana7/ExtraCoals"#https://github.com/ghana7/MinecraftCCG"
      logoFile="largelogo.png"
      credits=""
      authors="ghana7"
      description='''
      Adds a CCG to Minecraft
      '''

      [[dependencies.minecraftccg]]
        modId="forge"
        mandatory=true
        versionRange="[35,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.minecraftccg]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.4]"
        ordering="NONE"
        side="BOTH"